FAIRDataTeam/FAIRDataPoint

pom.xml
src/main/java/nl/dtls/fairdatapoint/service/FairSearchClient.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairSearchClientImpl.java
src/main/resources/conf/fdpConfig.yml
src/test/java/nl/dtls/fairdatapoint/service/impl/FairSearchClientImplTest.java

I implemented the feature to ping search engine. In the current Implementation the search is notified when any new metadata is added to the FDP and when the repository metadata is updated. My current implementation has a service interface to interact with search and I implemented this interface based on unirest.

Ping search feature

---

src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java

I've added some style changes as well, assuming a max line width of 100 characters. The extra check for unknown metadata type is not the cleanest solution, and definitely not something we can easily test. So I'd like some input on that.

Added logic for propagating the updates on metadata upward to the parents

---

Dockerfile
dockerSetup.sh

I made an attempt to trigger docker image build in hub.docker.com. I added docker and setup.sh files to the repository to enable auto build

Dockerfile setup

---

src/main/webapp/WEB-INF/templates/base.hbs
src/main/webapp/WEB-INF/templates/catalog.hbs
src/main/webapp/WEB-INF/templates/dataset.hbs
src/main/webapp/WEB-INF/templates/distribution.hbs
src/main/webapp/WEB-INF/templates/repository.hbs

Added the additional fields to the handlebars templates for metadata properties.

Show all properties in the HTML view

---

src/main/java/nl/dtls/fairdatapoint/api/config/RootConfig.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataMetricsServiceImpl.java
src/main/resources/conf/fdpConfig.yml
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java

An implementation of generic configuration of metrics. In the current approach I am creating a Map object bean for metrics, with metric nanpub URI as a key for the map and the metric value as a map value.

Metrics configuration

---

src/main/java/nl/dtls/fairdatapoint/api/config/RestApiContext.java
src/main/java/nl/dtls/fairdatapoint/api/config/SecurityConfig.java
src/test/java/nl/dtls/fairdatapoint/api/config/TestAgraphStoreConfig.java
src/test/java/nl/dtls/fairdatapoint/api/config/TestBlazegraphStoreConfig.java
src/test/java/nl/dtls/fairdatapoint/api/config/TestGraphDBStoreConfig.java
src/test/java/nl/dtls/fairdatapoint/api/config/TestNativeStoreConfig.java
src/test/java/nl/dtls/fairdatapoint/api/controller/MetadataControllerAdviceTest.java
src/test/java/nl/dtls/fairdatapoint/api/controller/MetadataControllerTest.java
src/test/java/nl/dtls/fairdatapoint/repository/impl/StoreManagerImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairSearchClientImplTest.java

Existing test classes are modified and new test classes are added to increase the test coverage

Test coverage

---

src/main/webapp/WEB-INF/templates/base.hbs
src/main/webapp/WEB-INF/templates/catalog.hbs
src/main/webapp/WEB-INF/templates/dataset.hbs
src/main/webapp/WEB-INF/templates/distribution.hbs
src/main/webapp/WEB-INF/templates/repository.hbs

Updated bootstrap to 4.1 and migrated some 3.3.7 elements to 4.x. In the base template I've added blocks to render the metrics in a basic way.

Updated CSS in the UI

---

src/main/webapp/WEB-INF/templates/dataset.hbs

Quick fix, removed the lingering h4 tags that @rajaram5 discovered.

Removed lingering h4 tags

---

src/main/java/nl/dtls/fairdatapoint/service/PIDSystem.java

I have added a interface for PID system

PID interface

---

.gitignore
src/main/java/nl/dtls/fairdatapoint/api/config/RestApiContext.java
src/main/java/nl/dtls/fairdatapoint/api/config/RestApiTestContext.java
src/main/java/nl/dtls/fairdatapoint/service/impl/DefaultPIDSystemImpl.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/test/java/nl/dtls/fairdatapoint/service/impl/DefaultPIDSystemImplTest.java

Hi have implemented "DefaultPIDSystem" in the current implementation I am not using the "PIDSystem" configuration options yet

DefaultPIDSystem

---

src/main/java/nl/dtls/fairdatapoint/api/config/RestApiContext.java
src/main/java/nl/dtls/fairdatapoint/api/config/RestApiTestContext.java
src/main/java/nl/dtls/fairdatapoint/repository/StoreManager.java
src/main/java/nl/dtls/fairdatapoint/repository/impl/StoreManagerImpl.java
src/main/java/nl/dtls/fairdatapoint/service/FairMetaDataService.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/main/java/nl/dtls/fairdatapoint/service/impl/PurlPIDSystemImpl.java
src/main/resources/conf/fdpConfig.yml
src/main/resources/nl/dtls/fairdatapoint/repository/impl/getFdpIri.sparql
src/main/resources/nl/dtls/fairdatapoint/utils/getFdpUriContent.ttl
src/test/java/nl/dtls/fairdatapoint/repository/impl/StoreManagerImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/PurlPIDSystemImplTest.java
src/test/java/nl/dtls/fairdatapoint/utils/ExampleFilesUtils.java

I have implemented purl.org pid system and I also made the pid systems configurable

Implementation purl.org PID system

---

pom.xml
src/main/java/nl/dtls/fairdatapoint/api/config/ApplicationSwaggerConfig.java
src/test/java/nl/dtls/fairdatapoint/api/controller/MetadataControllerTest.java

Dependencies are updated and MetadataControllerTest class is modified to resolve bean injection issues. Also I added an example test method based on MockMVC

Dependencies are updated

---

src/main/webapp/WEB-INF/templates/base.hbs

Meta tag added to the html page

robot.txt meta tag added

---

README.md
src/main/resources/application-development.yml

Updated readme to reflect need for jdk14+, and add draft section on mongo setup.

Readme improvements

---

.dockerignore
.github/workflows/main.yml
CHANGELOG.md
Dockerfile
Dockerfile.build
README.md
pom.xml
src/main/java/nl/dtls/fairdatapoint/service/profile/ProfileService.java

Upgraded to Java 15 and added `Dockerfile.build` that is contains stage for building the jar directly in Docker...

[FDP-564] Upgrade to Java 15

---

pom.xml
src/test/java/nl/dtls/fairdatapoint/WebIntegrationTest.java

Some of the tests were not discovered (as the name does not end with "Test"). Now more tests are discovered, to speed up I removed `@DirtiesContext` annotation.

Re-enable acceptance tests

---

src/main/java/nl/dtls/fairdatapoint/util/RdfIOUtil.java

Basic registration of the standard namespaces. Could be extended for non-standard namespaces.

Allow for registration of standard namespaces.

---

CHANGELOG.md
pom.xml
src/main/java/nl/dtls/fairdatapoint/api/controller/label/LabelController.java
src/main/java/nl/dtls/fairdatapoint/api/dto/label/LabelDTO.java
src/main/java/nl/dtls/fairdatapoint/config/CacheConfig.java
src/main/java/nl/dtls/fairdatapoint/service/label/LabelService.java

Refined PR from #150:
It uses dependency stored in our public Nexus using a fork in FAIRDataTeam organization: https://github.com/FAIRDataTeam/rdf-resource-resolver
It works without any issues in our CI. (I also had issues with GitHub Packages locally.)

[FDP-537] Add label resolution

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/service/metadata/common/AbstractMetadataService.java
src/main/java/nl/dtls/fairdatapoint/service/metadata/validator/MetadataValidator.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionCache.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionService.java
src/test/java/nl/dtls/fairdatapoint/service/metadata/generic/GenericMetadataServiceTest.java
src/test/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionCacheTest.java

[FDP-578] Fix creating child with multiple possible parents

---

src/main/java/nl/dtls/fairdatapoint/service/openapi/OpenApiGenerator.java

https://github.com/FAIRDataTeam/FAIRDataPoint-Docs/issues/35

Fix generated OpenAPI POST response

---

CHANGELOG.md
pom.xml
src/main/resources/application.yml

Fixed according to https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot

Hotfix 1.12.1

---

CHANGELOG.md
pom.xml
src/main/resources/application.yml

Based on PR #233 (but using our git flow to allow hotfix release asap)

Hotfix 1.12.4

---

pom.xml

Seems like this old dependency is no longer used (and actually contains vulnerability).

Remove Unirest dependency

---

.github/workflows/security.yml
SECURITY.md

- CodeQL as GitHub Action
- Snyk as GitHub Action

Add GitHub Actions CI for security

---

.github/workflows/build.yml

See https://github.com/ankane/setup-mongodb/issues/1

Fix MongoDB for Windows Github Action

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/index/IndexAdminController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/index/IndexEntryController.java
src/main/java/nl/dtls/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0004_Cleanup_Index.java
src/main/java/nl/dtls/fairdatapoint/service/index/entry/IndexEntryService.java
src/main/java/nl/dtls/fairdatapoint/service/index/event/EventService.java
src/main/java/nl/dtls/fairdatapoint/service/index/harvester/HarvesterService.java
src/test/java/nl/dtls/fairdatapoint/service/index/harvester/HarvesterServiceTest.java

Idea for future based on this... maybe we should prevent indexing itself somehow 😄

Clear old data before harvesting

---

.github/workflows/code-style.yml
.github/workflows/docker-publish.yml
.github/workflows/maven-verify.yml
.github/workflows/security.yml

- trigger on push only for default branch (`develop`)
- use concurrency control
fixes #627

prevent duplicate workflow runs

---

src/main/java/org/fairdatapoint/config/RepositoryConfig.java

use correct properties for draftsRepository

---

CHANGELOG.md
src/main/java/org/fairdatapoint/api/controller/metadata/GenericController.java

Fix listing records after publish

---

src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/development/schema/data/MetadataSchemaFixtures.java
src/test/java/nl/dtls/fairdatapoint/acceptance/schema/Import_POST.java

Fixed Import_POST, the MetaDataSchemaDTO are now valid object

fix: update Metadataschema, test fixtures should produce valid objects

---

.github/pull_request_template.md

Added a github PR template to remind users to update issue links, readme, docs, changelog, version, and so on, if applicable.

Github pull request  template

---

CHANGELOG.md
pom.xml
src/main/resources/application.yml

Updated fdp package version and changelog

Bump to 1.18.0
