src/main/java/nl/dtls/fairdatapoint/api/config/RestApiContext.java
src/main/java/nl/dtls/fairdatapoint/api/controller/MetadataController.java
src/test/java/nl/dtls/fairdatapoint/api/controller/MetadataControllerTest.java

In the previous implementation the default content type is HTML. This is, however problematic for tools like demonstrator to use FDP, since demonstrator uses blazegraph's API to store the metadata and we can't supply accept header to the blazegraph API calls. I have changed the default content type to text/turtle and I also changed the response of the metadata POST calls for response with metadata as a turtle string. I also modified controller's unit method to check the default content type

Default content type is changed

---

config/fdp-server.properties
config/triple-store.properties
src/main/java/nl/dtls/fairdatapoint/repository/impl/StoreManagerImpl.java
src/main/java/nl/dtls/fairdatapoint/service/FairMetaDataMetricsService.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataMetricsServiceImpl.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/main/resources/conf/fdpConfig.yml
src/test/java/nl/dtls/fairdatapoint/repository/impl/StoreManagerImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataMetricsServiceImplTest.java
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java

I added new service layer to the API which generates metrics RDF statements for all metadata layers. The metric values are configurable, it can be done via property file. I also modified the storage layer, in the new implementation the resources are retrieved based on context URI which let me to refactor FairData service class. I remove addAdditionalResource() method in this class. Since we are retrieving resources from the store based on context URI this method is no long required. I also removed unused property files

FAIRMetataMetric implemation 

---

src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/main/resources/conf/fdpConfig.yml
src/main/webapp/WEB-INF/templates/base.hbs
src/main/webapp/WEB-INF/templates/catalog.hbs
src/main/webapp/WEB-INF/templates/dataset.hbs
src/main/webapp/WEB-INF/templates/distribution.hbs
src/main/webapp/WEB-INF/templates/repository.hbs
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java

I modified the addDefaultValues method in the FairMetaDataServiceImpl service layer to add default access rights.  In the current implementation the metadata content has no access restriction at all.

Default accessRights feature

---

pom.xml
src/main/java/nl/dtls/fairdatapoint/api/config/RestApiContext.java
src/main/java/nl/dtls/fairdatapoint/api/config/RestApiTestContext.java
src/main/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImpl.java
src/main/resources/conf/fdpConfig.yml
src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataMetricsServiceImplTest.java

I added configuration to use graphDB and blazegraph triple store. In the current implementation we support 3 external triple stores(Agraph, graphDB, blazegraph), we also provide options to user to use native and in-memory store. I also changed the context of this test class "FairMetaDataMetricsServiceImplTest". In the current implementation I use private fields in the context class to get the triple stores properties. We could also capture these properties in a separate object but it is up to discussion anyway.

External triple store support 

---

src/main/java/nl/dtls/fairdatapoint/api/controller/MetadataController.java
src/main/java/nl/dtls/fairdatapoint/service/impl/DefaultPIDSystemImpl.java
src/test/java/nl/dtls/fairdatapoint/api/controller/MetadataControllerTest.java

I have removed ID param from the POST call request. In the current implementation I am checking duplicate POST calls meaning that a metadata content can be posted twice and our server won't check for this duplication

ID params is removed

---

src/test/java/nl/dtls/fairdatapoint/service/impl/FairMetaDataServiceImplTest.java

The old situation required the child timestamp to be before parent timestamp, but it should have been before-or-equal. It is now changed to after, which encompasses before and equal.

Updated test in the service layer to better handle race conditions in timestamps

---

README.md

The original link pointed to the (now archived) confluence page. Right now the spec link points to the master branch of the spec repository. Should it point to develop instead for the develop branch of this repository, and have the master branch of this repository point to the tagged release of the spec (once it's stable)?

Added link to the spec repository

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/index/AdminController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/index/PingController.java
src/main/java/nl/dtls/fairdatapoint/api/filter/LoggingFilter.java
src/main/java/nl/dtls/fairdatapoint/config/WebConfig.java
src/main/java/nl/dtls/fairdatapoint/service/UtilityService.java
src/main/java/nl/dtls/fairdatapoint/service/index/event/EventMapper.java
src/main/java/nl/dtls/fairdatapoint/service/index/event/EventService.java
src/main/java/nl/dtls/fairdatapoint/service/index/event/IncomingPingUtils.java
src/main/java/nl/dtls/fairdatapoint/service/index/webhook/WebhookMapper.java
src/main/java/nl/dtls/fairdatapoint/service/index/webhook/WebhookService.java
src/main/java/nl/dtls/fairdatapoint/util/HttpUtil.java
src/main/resources/META-INF/additional-spring-configuration-metadata.json
src/main/resources/application.yml

This solves the issue when FDP Index things that IP of proxy (or proxy of FDP-client) is the origin of pings and there for applies rate limits on all incoming pings together as from one source. Now (if enable as "behind proxy"), it first looks for IP from proxy-related headers, fallback to previously used `getRemoteAddr`.
Related to https://github.com/FAIRDataTeam/FAIRDataPoint-client/pull/37

[FDP-566] Use proxy headers if proxied

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/service/ping/PingService.java

This is backward compatible and allows:
```yaml
ping:
endpoint: http://example1.com, http://example2.com
ping:
endpoint: >
http://example1.com
http://example2.com
```
Traditional YAML lists would be more complicated as cannot be simple parsed by `@Value`.

[FDP-557] Allow multiple ping endpoints

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/apikey/ApiKeyController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/config/ConfigController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/dashboard/DashboardController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/exception/ExceptionControllerAdvice.java
src/main/java/nl/dtls/fairdatapoint/api/controller/index/IndexEntryController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/index/PingController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/index/SettingsController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/membership/MembershipController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericMemberController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericMetaController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/profile/ProfileController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/resource/ResourceDefinitionController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/search/SearchController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/shape/ShapeController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/token/TokenController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/user/UserController.java
src/main/java/nl/dtls/fairdatapoint/api/dto/metadata/MetaDTO.java
src/main/java/nl/dtls/fairdatapoint/config/OpenApiConfig.java
src/main/java/nl/dtls/fairdatapoint/service/openapi/OpenApiGenerator.java
src/main/java/nl/dtls/fairdatapoint/service/openapi/OpenApiService.java
src/main/java/nl/dtls/fairdatapoint/service/openapi/OpenApiTagsUtils.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionService.java

It generates OpenAPI docs for endpoints related to resource definitions (all on startup and then on create, update, and delete of a resource definition).
- This should be rebased after merging pagination feature as there will be also generic endpoints.
- Should we also order somehow the tags (groups of endpoints)? Those are named `Metadata: <name>` but appear at the end...
TODOs:

[FDP-544][FDP-567] OpenAPI for generic endpoints and with response types

---

.github/workflows/main.yml
CHANGELOG.md
Dockerfile
Dockerfile.build
README.md
pom.xml

Java SE 15 support ended in March 2021. Java SE 16 will be supported till September 2021 and then we can finally switch to LTS (Java 17) that will have extended support for several years (TBA).

Upgrade to Java 16

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/development/shape/data/ShapeFixtures.java
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/production/Migration_0008_ShapesInternalChange.java
src/main/java/nl/dtls/fairdatapoint/service/shape/ShapeService.java
src/test/java/nl/dtls/fairdatapoint/acceptance/shape/Detail_DELETE.java
src/test/java/nl/dtls/fairdatapoint/acceptance/shape/Detail_PUT.java

Now it is possible to change internal shapes (but not delete them). Both dataset and distribution are no longer marked as internal; therefore, can be even deleted.

[FDP-570] Allow to change internal shapes

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/reset/ResetController.java
src/main/java/nl/dtls/fairdatapoint/api/dto/reset/ResetDTO.java
src/main/java/nl/dtls/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0001_Init.java
src/main/java/nl/dtls/fairdatapoint/entity/resource/ResourceDefinition.java
src/main/java/nl/dtls/fairdatapoint/entity/resource/ResourceDefinitionChildListView.java
src/main/java/nl/dtls/fairdatapoint/service/reset/FactoryDefaults.java
src/main/java/nl/dtls/fairdatapoint/service/reset/ResetService.java
src/main/resources/nl/dtls/fairdatapoint/service/reset/shape-catalog.ttl
src/main/resources/nl/dtls/fairdatapoint/service/reset/shape-dataset.ttl
src/main/resources/nl/dtls/fairdatapoint/service/reset/shape-distribution.ttl
src/main/resources/nl/dtls/fairdatapoint/service/reset/shape-repository.ttl
src/main/resources/nl/dtls/fairdatapoint/service/reset/shape-resource.ttl

This allows admins to trigger reset of FDP data:
- users (including permissions given to metadata and API keys)
- metadata (including permissions)
- resource definitions (including SHACL shapes and metadata)

[FDP-561] Allow reset to defaults

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/resource/ResourceDefinitionController.java
src/main/java/nl/dtls/fairdatapoint/api/dto/resource/ResourceDefinitionChangeDTO.java
src/main/java/nl/dtls/fairdatapoint/api/dto/resource/ResourceDefinitionDTO.java
src/main/java/nl/dtls/fairdatapoint/api/dto/shape/ShapeDTO.java
src/main/java/nl/dtls/fairdatapoint/config/CacheConfig.java
src/main/java/nl/dtls/fairdatapoint/config/MongoConfig.java
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/development/resource/data/ResourceDefinitionFixtures.java
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/development/shape/data/ShapeFixtures.java
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/production/Migration_0009_ShapeTargetClasses.java
src/main/java/nl/dtls/fairdatapoint/database/mongo/repository/ResourceDefinitionRepository.java
src/main/java/nl/dtls/fairdatapoint/entity/resource/ResourceDefinition.java
src/main/java/nl/dtls/fairdatapoint/entity/shape/Shape.java
src/main/java/nl/dtls/fairdatapoint/service/config/ConfigService.java
src/main/java/nl/dtls/fairdatapoint/service/metadata/enhance/MetadataEnhancer.java
src/main/java/nl/dtls/fairdatapoint/service/metadata/validator/MetadataValidator.java
src/main/java/nl/dtls/fairdatapoint/service/profile/ProfileService.java
src/main/java/nl/dtls/fairdatapoint/service/reset/FactoryDefaults.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionMapper.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionService.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionTargetClassesCache.java
src/main/java/nl/dtls/fairdatapoint/service/shape/ShapeMapper.java
src/main/java/nl/dtls/fairdatapoint/service/shape/ShapeService.java
src/main/java/nl/dtls/fairdatapoint/service/shape/ShapeShaclUtils.java
src/test/java/nl/dtls/fairdatapoint/acceptance/shape/Detail_DELETE.java
src/test/java/nl/dtls/fairdatapoint/acceptance/shape/Public_GET.java
src/test/java/nl/dtls/fairdatapoint/service/index/harvester/HarvesterServiceTest.java

Not sure if we can easily remove target classes from resource definitions. It is used in many places, e.g., we use it for metadata to set `rdf:type`. This duplicates the information from shape, but in shape is it encoded only in RDF. What would be the best solution @kburger? Do we want to keep target classes for resource definitions or should it be always figured out from linked shapes?

[FDP-550] Use profile for conformsTo

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericMetaController.java
src/main/java/nl/dtls/fairdatapoint/api/dto/metadata/MetaDTO.java
src/main/java/nl/dtls/fairdatapoint/api/dto/metadata/MetaPathDTO.java

This fixes the incorrect child links that appeared in pagination result. It also adds ancestors path to `**/meta` which makes `**/expanded` no longer needed.
Closes #156

[FDP-577] Fix multiple children with the same child relation

---

CHANGELOG.md
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericMemberController.java
src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericMetaController.java
src/main/java/nl/dtls/fairdatapoint/service/metadata/factory/MetadataServiceFactory.java
src/main/java/nl/dtls/fairdatapoint/service/resource/ResourceDefinitionValidator.java
src/main/java/nl/dtls/fairdatapoint/util/HttpUtil.java
src/test/java/nl/dtls/fairdatapoint/acceptance/metadata/repository/Detail_POST.java
src/test/java/nl/dtls/fairdatapoint/acceptance/resource/Detail_PUT.java

This is still WIP (as I won't be able to work on this during few upcoming days). It should also use `recordId` from path to compose metadata URI instead of parsing and replacing URI from `HttpServletRequest`. The pattern with `[^.]+` is used to avoid conflicts with routes that have `.` in name, e.g. `/swagger-ui.html` and `/swagger-ui/index.html`.
However, there are some questions (@kburger):
- Is there any limitation with this approach that I overlooked?
- Can we set a rule for resource definition URL prefix to be composed only using `[a-z0-9-_~]+` (and empty for repository)?
- Should the regex be more permissive (e.g. forbid only `.html` suffix)?
- Any other thoughts?
(I also tested this with the newest SpringDoc OpenAPI-UI and it works, even without hacking `WebMvcConfigurer`.

Refactor wildcard paths

---

.github/workflows/main.yml
CHANGELOG.md
Dockerfile
Dockerfile.build
README.md
pom.xml

Finally LTS is here and should be supported until 2029. Updates for Java 16 end this month... ([wiki](https://en.wikipedia.org/wiki/Java_version_history))

Upgrade to Java 17

---

pom.xml
src/main/java/nl/dtls/fairdatapoint/config/MongoConfig.java

They also deprecated `@ChangeLog` and `@ChangeSet` annotations, but that must be the same for old migrations... However, new migrations should use `@ChangeUnit`: https://mongock.io/v5/from-version-4-to-5/
Luckily, we don't need the extra `mongo-driver-sync` dependency and it will allow to update `spring-boot` to 2.6+

Update to Mongock 5

---

CHANGELOG.md
pom.xml
src/main/resources/application.yml

Upgrade to Spring Boot 2.6.6 due to [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965) ([more info](https://spring.io/blog/2022/03/31/spring-boot-2-6-6-available-now))

Hotfix 1.13.1

---

src/main/java/nl/dtls/fairdatapoint/api/controller/search/SearchSavedQueryController.java
src/main/java/nl/dtls/fairdatapoint/service/search/SearchService.java

Adds `POST /search/query/saved/{uuid}` for executing directly the saved query identified by `{uuid}` path variable.

Allow direct search using saved query

---

src/main/java/nl/dtls/fairdatapoint/api/controller/metadata/GenericController.java
src/test/java/nl/dtls/fairdatapoint/acceptance/metadata/SingpostingTest.java

Draft of signposting headers. Nothing special right now, and a lot of decisions still have to be made.
The current logic is added to the controller directly, but it could just as easily be moved to a filter. Up for discussion.

Add initial signposting headers

---

pom.xml
src/main/java/org/fairdatapoint/config/RepositoryMigrationConfig.java
src/main/java/org/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0001_Init.java
src/main/java/org/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0002_Metadata_Draft.java
src/main/java/org/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0003_FDPO.java
src/main/java/org/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0004_Cleanup_Index.java
src/main/java/org/fairdatapoint/database/rdf/migration/production/Rdf_Migration_0005_FixMetadataVersion.java
src/main/java/org/fairdatapoint/service/label/LabelService.java
src/main/resources/application.yml

This PR fixes #574:
`spring-rdf-migration` from Maven Central repository. 
TODO: For this to work, we need to merge PRs for the dependencies and publish corresponding releases:

Get FAIR Data Team dependencies from Maven Central repository

---

pom.xml
src/main/java/org/fairdatapoint/api/controller/settings/SettingsDefaults.java
src/main/java/org/fairdatapoint/entity/schema/MetadataSchema.java
src/main/java/org/fairdatapoint/entity/schema/MetadataSchemaVersion.java
src/main/java/org/fairdatapoint/service/apikey/ApiKeyMapper.java
src/main/java/org/fairdatapoint/service/index/entry/IndexEntryService.java
src/main/java/org/fairdatapoint/service/resource/ResourceDefinitionMapper.java
src/main/java/org/fairdatapoint/service/schema/MetadataSchemaMapper.java
src/main/java/org/fairdatapoint/service/schema/MetadataSchemaService.java
src/main/java/org/fairdatapoint/service/search/query/SearchSavedQueryMapper.java
src/main/java/org/fairdatapoint/service/settings/SettingsService.java
src/main/java/org/fairdatapoint/service/user/UserMapper.java
src/test/java/org/fairdatapoint/acceptance/index/entry/List_All_GET.java
src/test/java/org/fairdatapoint/utils/TestIndexEntryFixtures.java

spring-boot 3.2.12 -> 3.4.1
springdoc 2.5.0 -> 2.8.3
postgresql 42.7.3 -> 42.7.5
rdf4j 4.3.12 -> 5.1.0
lombok 1.18.32 -> 1.18.36
hypersistence 3.7.6 -> 3.9.0
httpclient5 5.3.1 -> 5.4.1

Update core dependencies

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml

- fixes duplicate ids in feature-request template
- enables *blank* issues:
Although issue *templates* are useful when used properly, I see several drawbacks:
- increased threshold for reporting issues (reporter's time is valuable!)
- increased maintenance burden (current PR is template maintenance...)
- often too restrictive or not a good fit
- often too verbose
By enabling blank issues, reporter gets to choose.

Fix issue templates

---

src/main/java/org/fairdatapoint/api/controller/metadata/GenericController.java

Using `compareToIgnoreCase()` instead of `compareTo()`.
Note: maybe a good idea also to check the other uses of `compareTo` in the codebase...
fixes #676

Ignore case when sorting resources by title

---

.github/workflows/code-style.yml
.github/workflows/docker-publish.yml
.github/workflows/maven-verify.yml
.github/workflows/security.yml
CHANGELOG.md
Dockerfile
README.md
pom.xml
src/main/java/nl/dtls/fairdatapoint/database/mongo/migration/development/schema/data/MetadataSchemaFixtures.java
src/main/java/nl/dtls/fairdatapoint/service/jwt/JwtService.java
src/main/java/nl/dtls/fairdatapoint/service/metadata/state/MetadataStateService.java
src/test/java/nl/dtls/fairdatapoint/acceptance/openapi/SwaggerUI_GET.java
src/test/java/nl/dtls/fairdatapoint/acceptance/schema/Import_POST.java

Upgrade dependencies to match current develop branch:
- upgraded JDK from 17 to 21
- upgraded various dependencies in pom.xml
- removed redundant spring-data-mongodb version pin to fix conflict
- adapted deprecated references in `JwtService` class to match develop

Upgrade dependencies for v1.17.x

---

CHANGELOG.md
src/main/java/org/fairdatapoint/api/controller/exception/ExceptionControllerAdvice.java
src/main/java/org/fairdatapoint/service/schema/MetadataSchemaMapper.java
src/main/java/org/fairdatapoint/service/schema/MetadataSchemaService.java
src/test/java/org/fairdatapoint/acceptance/schema/Common.java
src/test/java/org/fairdatapoint/service/schema/MetadataSchemaServiceTests.java

closes #660 
to be _squash-merged_

Fix editing schema
